services:
  hugo-site:
    image: hugo-site:latest
    container_name: hugo-website
    restart : always
    ports:
      - "8015:80"
    networks:
      - front

networks:
  front:
    external: true