services:
  web:
    image: nginx:alpine
    ports:
      - "8002:80"
    volumes:
      - $path/htdocs/public/:/usr/share/nginx/html
      - $path/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - front

networks:
  front:
    external: true
